spring:
  application:
    name: Customer
  datasource:
    url: jdbc:mysql://localhost:3307/etiqatest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 7071

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
    operationsSorter: method

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


