spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/etiqatest
    username: root
    password: root
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  hazelcast:
    config: classpath:hazelcast.xml

server:
  port: 7070

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

logging:
  level:
    com.hazelcast: DEBUG
